name: docker-compose-mysql

services:
  docker-compose-mysql:
    image: mysql:8.4.3
    container_name: docker-compose-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3380:3306"