FROM alpine:3

LABEL author="Muhammad Aria Muktadir"
LABEL company="Aria's Lab" website="https://ariaslab.com"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD ["cat", "hello/world.txt"]