name: docker-compose-ports

services:
  nginx-port1:
    image: nginx:latest
    container_name: nginx-port1
    ports:
      - target: 80
        published: 8082
        protocol: tcp
  nginx-port2:
    image: nginx:latest
    container_name: nginx-port2
    ports:
      - "8083:80"